### PR TITLE
Worldpop explore

### PR DESCRIPTION
**Pull request by collaer**
Hey
I've just made a push request of a very simple notebook that:
1 dl manifest of data from worlpop
2 filter it for USA
3 download a first raster file of 5Gb for US population of 2010
4 clip it to a 5mb file for the bbox/extent of DC metro rea we are working on (my computer cannot host 200Gb of tiff file that are covering all US)
5 open the csv (from our slack) that is the template of the bg table
6 fill the population values column for the 25k points/entry

I will not merge my own PR it's against my religion (wich is a private pastafarism vision of mine).

Thanks if you can review and merge it.

I don't know if I will have more time to start implement real function to download and extrat all the data (land use, pop, road density etc) and fill it for each year but this first step is already there.

### CODE REVIEW

**Comment by collaer** [comment]
I updated the PR with some documentations about libraries to install. and a requierements.txt
There is a librairie to dl and install fron git for worldpop python api
A the gdal ogr lib that sometimes needs some OS dependants installation prior pip install it
Also added gitignore to subsequents files downloaded

**Comment by collaer** [comment]
I added a script who is doing for a configuration of config_worldpop dict config the extract and first munching step for worldpop data:
population
distance to main roads
slope
distance to forest
distance to coast

As we are changing from putting data to each of 25k points in metro area to focus on " only" locations/points of ground station the script must be adapted and run using the extract of ground station data.

I think it may be merge as first step along with the explanatory notebook.

**Comment by collaer** [comment]
#ready_to_merge
If you can review it, it is okay for me
to test it you have to follow MD instructions : 
python3 worldpop/load-wp.py --folder=GIS --csv=bigtable.csv
be sure to have replaced bigtable.csv by the csv issue by using the purpleair script (+openaq)

**Comment by ayeshabaig** [comment]
Are we populating all the data from the different sensors?

**Pull request merged**
